#!/usr/bin/env bash
# shellcheck shell=bash

# =============================================================================
# acc-manager — загрузка и настройка ACCWeb.
# =============================================================================

download_accweb() {
  if [[ -x "$ACCWEB_DIR/accweb" ]]; then
    info "ACCWeb уже установлен (${ACCWEB_DIR})."
    return 0
  fi

  info "Определение последней версии ACCWeb..."
  local release_json version asset_url tmp root_dir
  release_json="$(curl -fsSL "https://api.github.com/repos/${ACCWEB_REPO}/releases/latest")"
  version="$(printf '%s' "$release_json" | jq -r '.tag_name')"
  asset_url="$(printf '%s' "$release_json" | jq -r '.assets[] | select(.name | endswith(".zip")) | .browser_download_url' | head -n1)"

  if [[ -z "$asset_url" || "$asset_url" == "null" ]]; then
    die "Не удалось найти zip-архив ACCWeb в последнем релизе."
  fi

  info "Загрузка ACCWeb ${version}..."
  tmp="$(mktemp -d)"
  curl -fsSL "$asset_url" -o "$tmp/accweb.zip"
  unzip -q "$tmp/accweb.zip" -d "$tmp/extracted"

  root_dir="$(find "$tmp/extracted" -mindepth 1 -maxdepth 1 -type d | head -n1)"
  [[ -d "$root_dir" ]] || die "Не удалось распаковать архив ACCWeb."

  mkdir -p "$ACCWEB_DIR"
  cp -a "$root_dir"/. "$ACCWEB_DIR"/
  chmod +x "$ACCWEB_DIR/accweb" 2>/dev/null || true
  rm -rf "$tmp"

  info "ACCWeb ${version} установлен в ${ACCWEB_DIR}."
}

configure_accweb() {
  local web_port="$1" admin="$2" mod="$3" ro="$4"
  local host

  if [[ -f "$ACCWEB_DIR/config.yml" ]] && grep -q 'generated by acc-manager' "$ACCWEB_DIR/config.yml" 2>/dev/null; then
    info "ACCWeb уже настроен (config.yml существует), генерация пропущена."
    return 0
  fi

  host="0.0.0.0:${web_port}"

  render_template "$TEMPLATE_DIR/config.yml.tpl" "$ACCWEB_DIR/config.yml" \
    "ACCWEB_HOST=$(yaml_sq_escape "$host")" \
    "ACCWEB_ADMIN_PASSWORD=$(yaml_sq_escape "$admin")" \
    "ACCWEB_MOD_PASSWORD=$(yaml_sq_escape "$mod")" \
    "ACCWEB_RO_PASSWORD=$(yaml_sq_escape "$ro")" \
    "ACC_SERVER_PATH=$(yaml_sq_escape "$SERVER_DIR")" \
    "ACCWEB_CONFIG_PATH=$(yaml_sq_escape "$ACCWEB_CONFIG_DIR")"

  chown "$ACC_USER":"$ACC_USER" "$ACCWEB_DIR/config.yml"
  info "config.yml сгенерирован (server_path → ${SERVER_DIR})."
}
