# ACCWeb configuration (generated by acc-manager)
# https://github.com/assetto-corsa-web/accweb

webserver:
  host: '__ACCWEB_HOST__'
  tls: false
  cert: ''
  private_key: ''

  write_timeout: 5
  read_timeout: 5

auth:
  timeout: 20m
  admin_password: '__ACCWEB_ADMIN_PASSWORD__'
  moderator_password: '__ACCWEB_MOD_PASSWORD__'
  read_only_password: '__ACCWEB_RO_PASSWORD__'

acc:
  server_path: '__ACC_SERVER_PATH__'
  server_exe: accServer.exe

config_path: '__ACCWEB_CONFIG_PATH__'
dev: false
loglevel: info
cors:
  origins: '*'
  loglevel: info

log:
  with_timestamp: true

callback:
  enabled: false
